### PR TITLE
Start of conversion to Craft 2.5 to restore functionality in Nav.

### PR DESCRIPTION
**Pull request by lukeholder**
Also added an svg plugin icon and sidebar nav icon-mask svg. Feel free to use whatever and discard the pull request after.

### CODE REVIEW

**Comment by lukeholder** [comment]
Craft 2.5 beta will make the nav name configurable soon, so the plugin name and nav name can be different.

**Comment by hubertprein** [comment]
@lukeholder Thanks!

**Comment by lukeholder** [comment]
@hubertprein wasn't expecting a straight pull to master sorry, the minified version of the js was not compiled. Also, this will not work with pre - 2.5 Craft.

Anyways thanks!

**Pull request merged**
